name: habib_reminder
description: "A new Flutter project."

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ^3.8.1

dependencies:
  audioplayers: ^6.5.0
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.1.0
  get_storage: ^2.1.1
  launch_at_startup: ^0.5.1
  package_info_plus: ^8.3.0
  system_tray: ^2.0.3
  url_launcher: ^6.3.2
  window_manager: ^0.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/icons/
